
// GET
export const  GET_USERS_START="GET_USERS_START"
export const  GET_USERS_FAIL="GET_USERS_FAIL"
export const  GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const  GET_USERS_SAGA="GET_USERS_SAGA"


export const  POST_USERS_START="POST_USERS_START"
export const  POST_USERS_FAIL="POST_USERS_FAIL"
export const  POST_USERS_SUCCESS="POST_USERS_SUCCESS"
export const  POST_USERS_SAGA="POST_USERS_SAGA"

export const POST_TEAM_START="POST_TEAM_START"
export const POST_TEAM_SUCCESS="POST_TEAM_SUCCESS"
export const POST_TEAM_FAIL="POST_TEAM_FAIL"
export const  POST_TEAM_SAGA="POST_TEAM_SAGA"

export const GET_TEAM_START="GET_TEAM_START"
export const GET_TEAM_SUCCESS="GET_TEAM_SUCCESS"
export const GET_TEAM_FAIL="GET_TEAM_FAIL"
export const  GET_TEAM_SAGA="GET_TEAM_SAGA"

export const GET_TEAM_MEMBER_START="GET_TEAM_MEMBER_START"
export const GET_TEAM_MEMBER_SUCCESS="GET_TEAM_MEMBER_SUCCESS"
export const GET_TEAM_MEMBER_FAIL="GET_TEAM_MEMBER_FAIL"
export const  GET_TEAM_MEMBER_SAGA="GET_TEAM_MEMBER_SAGA"
